name: Bug Report
description: Report a bug in OpenLinkOS
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug. Please fill out the sections below to help us understand and reproduce the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Install packages...
        2. Create agent with...
        3. Call agent.run(...)
        4. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include error messages or stack traces if applicable.
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: input
    id: package
    attributes:
      label: Package
      description: Which OpenLinkOS package is affected?
      placeholder: e.g., @openlinkos/agent
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package Version
      description: The version of the affected package.
      placeholder: e.g., 0.1.0
    validations:
      required: true

  - type: dropdown
    id: node-version
    attributes:
      label: Node.js Version
      options:
        - "18.x"
        - "20.x"
        - "22.x"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might help (logs, screenshots, configuration).
      placeholder: Add any additional context here...
    validations:
      required: false
