name: Feature Request
description: Suggest a new feature for OpenLinkOS
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature. Please fill out the sections below to help us understand your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Describe the use case.
      placeholder: I'm trying to... but currently...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution. Include API examples or code snippets if possible.
      placeholder: |
        I'd like to be able to...

        ```typescript
        // Example API usage
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered? Why are they insufficient?
      placeholder: I've considered...
    validations:
      required: false

  - type: dropdown
    id: package
    attributes:
      label: Related Package
      description: Which package would this feature belong to?
      options:
        - "@openlinkos/ai"
        - "@openlinkos/agent"
        - "@openlinkos/subagent"
        - "@openlinkos/team"
        - "@openlinkos/mcp"
        - "@openlinkos/cli"
        - "Channel (Telegram, Feishu, Discord, Slack, DingTalk)"
        - "Plugin"
        - "New package"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information, mockups, or references that might help.
      placeholder: Add any additional context here...
    validations:
      required: false
